name: fiap-meetup
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - run: uname -a
      - run: id
      - run: env
      - run: df -h
      - run: cat /proc/cpuinfo
      - run: cat /proc/meminfo
      - run: dpkg -l
